"""Ask the council one investment question; write the deliberation as a memo.

    uv run python -m investment "Should I overweight semis?" [--context-file notes.md]

Requires the LLM Council service to be running (the llm-council/ lab in the
conductor repo). The service URL comes from COUNCIL_URL, default
http://localhost:8001.
"""

import argparse
import asyncio
import datetime
import re
import sys
from pathlib import Path

import httpx

from .briefs import build_brief
from .council_client import base_url, deliberate

DISCLAIMER = "> Research aid generated by a multi-model council. Not financial advice."


def slugify(question: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", question.lower()).strip("-")
    return slug[:max_len].rstrip("-") or "question"


def render_memo(question: str, result: dict, when: datetime.datetime) -> str:
    stage1 = result.get("stage1") or []
    stage3 = result.get("stage3") or {}
    metadata = result.get("metadata") or {}
    aggregate = metadata.get("aggregate_rankings") or []

    members = ", ".join(entry["model"] for entry in stage1)
    lines = [
        f"# Investment memo: {question}",
        "",
        f"*{when:%Y-%m-%d} · council: {members} · chairman: {stage3.get('model', 'unknown')}*",
        "",
        DISCLAIMER,
        "",
        "## Chairman's synthesis",
        "",
        stage3.get("response", "(no synthesis returned)"),
        "",
    ]

    if aggregate:
        lines += [
            "## Council standings",
            "",
            "Peer-ranked with identities anonymized; lower average is better.",
            "",
            "| # | Model | Avg rank | Votes |",
            "|---|-------|----------|-------|",
        ]
        lines += [
            f"| {position} | {entry['model']} | {entry['average_rank']} | {entry['rankings_count']} |"
            for position, entry in enumerate(aggregate, start=1)
        ]
        lines.append("")

    if stage1:
        lines += ["## Appendix: individual analyses", ""]
        for entry in stage1:
            lines += [f"### {entry['model']}", "", entry["response"], ""]

    return "\n".join(lines)


def main(argv: list[str] | None = None, transport: httpx.AsyncBaseTransport | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="investment", description="Council-backed investment research memo"
    )
    parser.add_argument("question", help="The investment question to deliberate")
    parser.add_argument(
        "--context-file",
        type=Path,
        help="Optional file whose contents are given to every analyst as context",
    )
    parser.add_argument(
        "--out-dir", type=Path, default=Path("memos"), help="Where to write the memo"
    )
    args = parser.parse_args(argv)

    context = args.context_file.read_text() if args.context_file else None
    brief = build_brief(args.question, context)

    try:
        result = asyncio.run(deliberate(brief, transport))
    except httpx.ConnectError:
        print(
            f"Council service not reachable at {base_url()}.\n"
            "Start it from the conductor repo: cd llm-council && uv run python -m backend.main\n"
            "(or point COUNCIL_URL at a running instance).",
            file=sys.stderr,
        )
        return 1

    when = datetime.datetime.now()
    memo = render_memo(args.question, result, when)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    memo_path = args.out_dir / f"{when:%Y-%m-%d-%H%M}-{slugify(args.question)}.md"
    memo_path.write_text(memo)

    print(result.get("stage3", {}).get("response", "(no synthesis returned)"))
    print(f"\nMemo written to {memo_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
